{% macro value(x) %}

CASE 
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (1) THEN 'JAN'
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (2) THEN 'FEB'
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (3) THEN 'MAR'
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (4) THEN 'APR'
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (5) THEN 'MAY'
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (6) THEN 'JUN'
WHEN MONTH(TO_TIMESTAMP({{x}})) IN (7) THEN 'JUL'
ELSE 'NO_MONTH'
END 

{% endmacro %}